/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AuthProviderService } from "../authProvider.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AuthProviderCreateInput } from "./AuthProviderCreateInput";
import { AuthProvider } from "./AuthProvider";
import { AuthProviderFindManyArgs } from "./AuthProviderFindManyArgs";
import { AuthProviderWhereUniqueInput } from "./AuthProviderWhereUniqueInput";
import { AuthProviderUpdateInput } from "./AuthProviderUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AuthProviderControllerBase {
  constructor(
    protected readonly service: AuthProviderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AuthProvider })
  @nestAccessControl.UseRoles({
    resource: "AuthProvider",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAuthProvider(
    @common.Body() data: AuthProviderCreateInput
  ): Promise<AuthProvider> {
    return await this.service.createAuthProvider({
      data: data,
      select: {
        clientId: true,
        clientSecret: true,
        createdAt: true,
        deletedAt: true,
        id: true,
        name: true,
        redirectUri: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AuthProvider] })
  @ApiNestedQuery(AuthProviderFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AuthProvider",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async authProviders(@common.Req() request: Request): Promise<AuthProvider[]> {
    const args = plainToClass(AuthProviderFindManyArgs, request.query);
    return this.service.authProviders({
      ...args,
      select: {
        clientId: true,
        clientSecret: true,
        createdAt: true,
        deletedAt: true,
        id: true,
        name: true,
        redirectUri: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AuthProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AuthProvider",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async authProvider(
    @common.Param() params: AuthProviderWhereUniqueInput
  ): Promise<AuthProvider | null> {
    const result = await this.service.authProvider({
      where: params,
      select: {
        clientId: true,
        clientSecret: true,
        createdAt: true,
        deletedAt: true,
        id: true,
        name: true,
        redirectUri: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AuthProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AuthProvider",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAuthProvider(
    @common.Param() params: AuthProviderWhereUniqueInput,
    @common.Body() data: AuthProviderUpdateInput
  ): Promise<AuthProvider | null> {
    try {
      return await this.service.updateAuthProvider({
        where: params,
        data: data,
        select: {
          clientId: true,
          clientSecret: true,
          createdAt: true,
          deletedAt: true,
          id: true,
          name: true,
          redirectUri: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AuthProvider })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AuthProvider",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAuthProvider(
    @common.Param() params: AuthProviderWhereUniqueInput
  ): Promise<AuthProvider | null> {
    try {
      return await this.service.deleteAuthProvider({
        where: params,
        select: {
          clientId: true,
          clientSecret: true,
          createdAt: true,
          deletedAt: true,
          id: true,
          name: true,
          redirectUri: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
